#!/usr/bin/env bash
# This script configures Haproxy load balancer in a server.

apt-get -y update
apt-get install -y haproxy=1.6.*
frontend_configuration="frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend juan-web-backend\n"
backend_configuration="backend juan-web-backend\n\tbalance roundrobin\n\tmode http\n\tserver web-01 100.27.3.168 check\n\tserver web-02 100.25.144.138 heck"
sed -i "20i \\\n$frontend_configuration\n$backend_configuration" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
